### ISSUE TITLE
Device profile changes in 4.5.0 webui fault

### ISSUE THREAD

**Issue by ccall48** [chirpstack/chirpstack#282] opened 2023-09-27 02:00 UTC
Device profiles can be created in v4.5.0 but any configuration or codec changes after creation do not register as being altered or saved in the db. It also does not go back to the device profile screen like previous on hitting the submit/save to configuration or codec changes.

The rest api and rpc still seem to be working correctly.

> For the moment I have dropped back to v4.4.3 which I have confirmed has this working.

**Comment by brocaar** [comment] 2023-09-27 11:29
Thanks for reporting this issue, I'm going to look into this right now :-)

**Comment by brocaar** [comment] 2023-09-27 11:37
So far I have not been able to reproduce this:

* Tested using Firefox and Chrome
* I created a "test profile" with standard JS codec template, clicking *Submit* takes me to the list of profiles
* I click the *test profile* and change the `temp` field in the JS codec template, clicking *Submit* takes me to the list of profiles
* I click the *test profile* and the `temp` field in the JS codec reflect the latest change

Have you tried to refresh / clear your browser cache to make sure your browser is using the latest front-end code and sources?

Please let me know if there is anything else I can do to reproduce this issue.

**Comment by ccall48** [comment] 2023-09-27 12:58
I just rechecked, it seems once the device profile has been assigned to a device is when it occurs for me in the UI.

**Comment by vbulbul** [comment] 2023-09-28 15:13
I have same issue, cant submit changes. Version is updated to 4.5.0

**Comment by ccall48** [comment] 2023-09-29 04:00
I have taken another recording with browser dev tools open. it does mention some label not being correct on that page, but if that has anything to do with it or not i do not know.

https://cdn.discordapp.com/attachments/1088316656901689344/1157164077941018674/Screen_Recording_2023-09-29_at_13.55.17.mov

**Comment by skiplyfrance** [comment] 2023-09-29 06:12
Confirmed on my side. It works until the device profile is affected to minimum one device.

**Comment by brocaar** [comment] 2023-09-29 08:50
With the help of @skiplyfrance I have found the issue. The issue is the measurements tab, with the migration to the latest ReactJS + Ant versions, something has changes with regards to the name field validation. If you have that tab open, you will see a validation issue, which is the reason why the form does not submit. I will create a fix for this.

Thanks @ccall48 and @skiplyfrance to help me with debugging this issue :+1:

**Comment by ccall48** [comment] 2023-09-29 08:59
cool beans, at least i know i wasn't going crazy now 😅 

tbh i only found it by chance when i was trying to help somebody on discord with a payload decoder.

**Comment by brocaar** [comment] 2023-09-29 09:20
@ccall48 @skiplyfrance would the following error notification be helpful to add to all the forms in case of a validation error?

![image](https://github.com/chirpstack/chirpstack/assets/165497/f23c1a3b-b7ca-45ef-ab0b-594a8c2ae4a8)

The actual validation error is displayed per input field:

![image](https://github.com/chirpstack/chirpstack/assets/165497/1b35c8b5-6081-46e0-93fb-6acbce555f6c)

**Comment by skiplyfrance** [comment] 2023-09-29 09:37
It would definitly help. Maybe "Please complete all required fields." could be more explicit but I'm not a native english speaker.

**Comment by brocaar** [comment] 2023-09-29 09:44
In this case it is an empty required field, but in general this error will be triggered in case of all validation errors, thus also:

* Optional fields with incorrect input
* Required fields that have incorrect input

**Closed** 2023-09-29 09:47 UTC

**Comment by brocaar** [comment] 2023-09-29 09:48
The above commit fixes this issue + I have added this fix to all other forms as well to make sure the form behavior is equal to all forms.
