### ISSUE TITLE
LNS queues NewChannelRequests forever

### ISSUE THREAD

**Issue by trivialkettle** [chirpstack/chirpstack#337] opened 2023-12-13 12:51 UTC
Hi,
ChirpStack version: 4.6.0

ChirpStack tries to send `NewChannelRequests` to my devices, containing channels that the devices already send on.

Since the devices don't support MAC packages on fport 0 (LMIC stack), they can't handle the packages. Though I would expect ChirpStack to send it only once because its `Unconfirmed`

Here you can see a picture of the frames of one of this devices. As you can see, the Unconfirmed data down is not always sent.
![frames](https://github.com/chirpstack/chirpstack/assets/126059809/1c28fd78-7f3d-4e47-9a17-9057d9025968)

Payload of the downlink:
![frame](https://github.com/chirpstack/chirpstack/assets/126059809/754779cd-1385-427c-92a2-a8af67b89169)

Sometimes the frame also contains the payload `3: "DevStatusReq"`

The metrics of the device look pretty good to me and as you can see, the device already sends on the requested frequencies:
![metrics](https://github.com/chirpstack/chirpstack/assets/126059809/32ec1473-b837-42a0-9dde-b87318d4e9d3)

So I think there are two issues her:
1. My device does not support MAC in fport 0 -> we need a mechanism to split bigger payloads into smaller in `fopts`
2. Why does ChirpStack sends `NewChannelRequests` if the device already sends on this channels?
   Could it be, that the device sends on more channels than ChirpStack expects it to? 

Please let me know if you need any other information.
Thank you very much.

Edit:
chirpstack gateway bridge in `docker-compose.yml`:
```
# docker-compose.yml
  chirpstack-gateway-bridge-eu868:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    environment:
      - INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}
      - INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}
      - INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE=eu868/gateway/{{ .GatewayID }}/command/#
      - INTEGRATION__MQTT__AUTH__GENERIC__USERNAME=$MQTT_CHIRPSTACK_USERNAME
      - INTEGRATION__MQTT__AUTH__GENERIC__PASSWORD=$MQTT_CHIRPSTACK_PASSWORD
    depends_on:
      - mosquitto
    logging:
      options:
        max-file: "3"
        max-size: "100m"
```

chirpstack-gateway-bridge.toml
```
# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
```

edit2:
My chirpstack v3 config, where some extra channels were set:
```
...
[network_server.band]
name="EU868"

[network_server.network_settings]

  # Class A RX1 delay
  #
  # 0=1sec, 1=1sec, ... 15=15sec. A higher value means ChirpStack Network Server has more
  # time to respond to the device as the delay between the uplink and the
  # first receive-window will be increased.
  rx1_delay=5

  [[network_server.network_settings.extra_channels]]
  frequency=867100000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=867300000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=867500000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=867700000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=867900000
  min_dr=0
  max_dr=5
...
```

**Comment by brocaar** [comment] 2023-12-14 11:30
> My device does not support MAC in fport 0 -> we need a mechanism to split bigger payloads into smaller in fopts

I'm not going to implement a mechanism to split mac-commands into smaller fopts. Sending mac-commands using `fPort=0` is valid since the early days of LoRaWAN and it should be supported by LoRaWAN devices.

> Why does ChirpStack sends NewChannelRequests if the device already sends on this channels?

ChirpStack keeps an internal state of each device, you can print this state using `print-ds` sub-command, e.g.

```
chirpstack -c print-ds --dev-eui 0102030405060708
```

It will send mac-commands when the internal state is out-of-sync with the network configuration.

**Comment by trivialkettle** [comment] 2023-12-14 11:53
Hi,
thanks for the fast response
> I'm not going to implement a mechanism to split mac-commands into smaller fopts. Sending mac-commands using fPort=0 is valid since the early days of LoRaWAN and it should be supported by LoRaWAN devices.

Fair enough, I see the issue here. Unfortunately I cannot change the devices. Would you be interested in a pull request for this?
E.g. a option in device profiles?

I queried the internal stage, please see below.
What exactly is related here? I guess `enabledUplinkChannelIndices`?
What channels does ChirpStack use? I could not find any specific channel configuration for Eu868 in https://lora-alliance.org/wp-content/uploads/2021/05/RP002-1.0.3-FINAL-1.pdf

I could find only this:
> The network channels can be freely attributed by the network operator. However, the three422
following default channels SHALL be implemented in every EU863-870 end-device. Those423
channels are the minimum set that all network gateways SHALL be listening on.

And in the ChirpStack gateway bridge config:
```
# Region.
  #
  # Please refer to the LoRaWAN Regional Parameters specification
  # for the complete list of common region names.
  region="EU868"

  # Minimal frequency (Hz).
  frequency_min=863000000

  # Maximum frequency (Hz).
  frequency_max=870000000
```

are no channel indices mapped to frequencies.

I know that one could specify the channels in chirpstack v3.

Internal state of one device:
```
$ chirpstack -c /etc/chirpstack print-ds --dev-eui xxxx
{
  "devEui": "xxxx",
  "devAddr": "yyyy",
  "joinEui": "zzzz",
  "macVersion": "LORAWAN_1_0_2",
  "fNwkSIntKey": "xyz",
  "sNwkSIntKey": "xyz",
  "nwkSEncKey": "xyz",
  "appSKey": {
    "aesKey": "xyz"
  },
  "fCntUp": 1634,
  "nFCntDown": 1259,
  "confFCnt": 1028,
  "rx1Delay": 1,
  "rx2Frequency": 869525000,
  "enabledUplinkChannelIndices": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7
  ],
  "nbTrans": 1,
  "adr": true,
  "uplinkAdrHistory": [
    {
      "fCnt": 1614,
      "maxSnr": 9.5,
      "maxRssi": -58,
      "gatewayCount": 1
    },
    {
      "fCnt": 1615,
      "maxSnr": 9.0,
      "maxRssi": -56,
      "gatewayCount": 1
    },
    {
      "fCnt": 1616,
      "maxSnr": 9.5,
      "maxRssi": -58,
      "gatewayCount": 1
    },
    {
      "fCnt": 1617,
      "maxSnr": 9.8,
      "maxRssi": -58,
      "gatewayCount": 1
    },
    {
      "fCnt": 1618,
      "maxSnr": 9.2,
      "maxRssi": -59,
      "gatewayCount": 1
    },
    {
      "fCnt": 1619,
      "maxSnr": 7.0,
      "maxRssi": -65,
      "gatewayCount": 1
    },
    {
      "fCnt": 1620,
      "maxSnr": 9.8,
      "maxRssi": -60,
      "gatewayCount": 1
    },
    {
      "fCnt": 1621,
      "maxSnr": 9.8,
      "maxRssi": -61,
      "gatewayCount": 1
    },
    {
      "fCnt": 1622,
      "maxSnr": 8.0,
      "maxRssi": -61,
      "gatewayCount": 1
    },
    {
      "fCnt": 1623,
      "maxSnr": 8.8,
      "maxRssi": -61,
      "gatewayCount": 1
    },
    {
      "fCnt": 1624,
      "maxSnr": 10.8,
      "maxRssi": -65,
      "gatewayCount": 1
    },
    {
      "fCnt": 1625,
      "maxSnr": 7.5,
      "maxRssi": -72,
      "gatewayCount": 1
    },
    {
      "fCnt": 1626,
      "maxSnr": 9.5,
      "maxRssi": -66,
      "gatewayCount": 1
    },
    {
      "fCnt": 1627,
      "maxSnr": 7.8,
      "maxRssi": -71,
      "gatewayCount": 1
    },
    {
      "fCnt": 1628,
      "maxSnr": 8.0,
      "maxRssi": -66,
      "gatewayCount": 1
    },
    {
      "fCnt": 1629,
      "maxSnr": 9.2,
      "maxRssi": -64,
      "gatewayCount": 1
    },
    {
      "fCnt": 1630,
      "maxSnr": 10.2,
      "maxRssi": -63,
      "gatewayCount": 1
    },
    {
      "fCnt": 1631,
      "maxSnr": 8.0,
      "maxRssi": -74,
      "gatewayCount": 1
    },
    {
      "fCnt": 1632,
      "maxSnr": 7.5,
      "maxRssi": -60,
      "gatewayCount": 1
    },
    {
      "fCnt": 1633,
      "maxSnr": 9.0,
      "maxRssi": -62,
      "gatewayCount": 1
    }
  ],
  "lastDeviceStatusRequest": "2023-12-13T17:11:35.681246569+00:00",
  "regionConfigId": "eu868"
}
```

**Comment by trivialkettle** [comment] 2023-12-14 12:28
Thanks for the help. As edited I found the `region_eu868.toml` config

> I don't want to sound harsh, I just want to make sure that the code-base stays as clean as possible :-)

No worries, I totally understand this.

So that means, that the extra uplink channels somehow got lost, as it worked until recently.
Since my device does not accept the fport0 MAC, do you have any idea how I could work aorund this?

My ideas:
* disable extra channels (I don't know about the consequences)
* disable extra channels and enable them one by one and hope a single extra channel fits into fopts (maybe you could confirm this?). Though this means I have to repeat it every time a new device is added etc.

**Comment by brocaar** [comment] 2023-12-14 14:22
It could be caused by the ADRACKReq, which could reset the state back to default channels.

> disable extra channels (I don't know about the consequences)

This should fix the issue. The only downside is less bandwidth (3 channels instead of 8).

**Comment by trivialkettle** [comment] 2023-12-14 14:36
> It could be caused by the ADRACKReq, which could reset the state back to default channels.

I cannot see this flag in the database / integration database, correct? All the frames I checked by hand in ChirpStack GUI showed the flag = false, though there are only 5 frames per device and the problem is there for some days.

Thanks for your help so far.

In the case I need to fix this in my ChirpStack fork, could you briefly describe what I need to consider?
I know that the relevant code is here: https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/downlink/data.rs#L718

**Comment by brocaar** [comment] 2023-12-18 15:10
You could change this https://github.com/chirpstack/chirpstack/blob/master/chirpstack/src/downlink/data.rs#L675 to collect to up to 15 bytes, but in case a mac-command block is > 15 bytes (not sure if that would happen), then it will never been sent to the device.

I would change the region config to only use the default channels, no additional channels. Then you don't have to make any code changes.

I'm closing this issue as this is not a ChirpStack bug.

**Closed by brocaar** 2023-12-18 15:10 UTC
